name: Build and Push backend to GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push backend Docker image
        with:
          image: pdfui
          addLatest: true
          registry: ghcr.io
          # githubOrg: override-org # optional
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./Dockerfile

      - name: Trigger deployment
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"folder": "pdfui"}' \
            https://bf0.ch/hooks/deploy-service
